<?php
// call the 'prepare' to fill initial data and adjust the form properties, if needed
$this->form1->setAttribute('class', 'form-horizontal');
$this->form1->prepare();

echo $this->form()->openTag($this->form1);
echo '<fieldset>';

// following helper builds the form elements
// echo $this->formCollection($this->form1);

foreach($this->form1 as $element) {
    if (!($element instanceof Zend\Form\Element\Submit)) {
?>
<div class="control-group">
    <label class="control-label" for="<?php echo $element->getName(); ?>">
        <?php echo $this->translate($element->getLabel()); ?>
    </label>
    <div class="controls">
        <?php
            echo $this->formElement($element);
            echo $this->formElementErrors($element);
        ?>
    </div>
</div>
<?php
    } else {
        $element->setAttribute('class', 'btn btn-primary');
?>
        <div class="form-actions">
        <?php echo $this->formElement($element); ?>
        </div>
<?php
    }
}

echo '</fieldset>';
echo $this->form()->closeTag($this->form1);
