<h1>Top Line</h1>                                                                                                                                                                           
<?php echo $this->content; ?>                                                                                                                                                               
<h1>Bottom Line</h1>

